version: '3.8'
services:

  db: 
    image: mysql:5.7 
    restart: always
    command: --lower_case_table_names=1
    container_name: Probrain_db
    ports:
      - "${MYSQL_PORT}:3306" 
    env_file: .env
    build: ./
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
  dev_db: 
    image: mysql:5.7 
    restart: always
    command: --lower_case_table_names=1
    container_name: dev_db
    ports:
      - "${MYSQL_PORT}:3306" 
    env_file: .env
    build: ./
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./dev/conf.d:/etc/mysql/conf.d
      - ./dev/data:/var/lib/mysql
      - ./dev/initdb.d:/docker-entrypoint-initdb.d      

  redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: Probrain_redis
      hostname: redis_boot
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - ${REDIS_PORT}:6379
