version: '3.8'
services:

  mariadb:
    image: mariadb:10.4.6
    container_name: Probrain_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      TZ: Asia/Seoul
    volumes:
     - ./db_volumes:/var/lib/mysql
    ports:
     - '4123:3306'
    command:
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_general_ci

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "probrain"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
    ports:
      - 4125:3306 
    container_name: example_mysql  
  redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: Probrain_redis
      hostname: redis_boot
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 4124:6379
